const razones = [

"Porque desde el primer ensayo de tinkus llamaste mi atención.",
"Porque nunca imaginé que un ensayo cambiaría mi vida para siempre.",
"Porque gracias al tinku tuve la suerte de conocerte.",
"Porque tu sonrisa fue lo primero que me enamoró.",
"Porque contigo todo se siente más bonito.",
"Porque haces que hasta los días difíciles valgan la pena.",
"Porque tu risa siempre mejora mi día.",
"Porque me encanta escuchar tu voz.",
"Porque siempre pienso en ti sin darme cuenta.",
"Porque me haces sentir afortunado de tenerte.",

"Porque contigo puedo ser yo mismo.",
"Porque tus abrazos son mi lugar favorito.",
"Porque me das paz con solo estar cerca.",
"Porque haces especiales los momentos más simples.",
"Porque me encanta cuando sonríes.",
"Porque eres una persona increíble.",
"Porque haces que quiera ser mejor cada día.",
"Porque confías en mí.",
"Porque nunca me canso de hablar contigo.",
"Porque siempre consigues alegrarme.",

"Porque eres mi pensamiento favorito.",
"Porque contigo aprendí lo bonito que es amar.",
"Porque haces que mi corazón lata más fuerte.",
"Porque me inspiras todos los días.",
"Porque me encanta compartir tiempo contigo.",
"Porque el destino fue bueno al cruzar nuestros caminos.",
"Porque cada recuerdo contigo vale oro.",
"Porque eres mi lugar seguro.",
"Porque haces que todo tenga sentido.",
"Porque contigo cualquier lugar se siente perfecto.",

"Porque tu felicidad también es la mía.",
"Porque siempre quiero verte sonreír.",
"Porque me encanta hacerte reír.",
"Porque eres la mejor parte de mis días.",
"Porque nunca dejaré de admirarte.",
"Porque me haces sentir querido.",
"Porque tus ojitos tienen algo que me pierde.",
"Porque cada conversación contigo es especial.",
"Porque me encanta cómo eres.",
"Porque apareciste cuando menos lo esperaba.",

"Porque me haces creer en el destino.",
"Porque cada vez que escucho un tinku me acuerdo de ti.",
"Porque jamás olvidaré el lugar donde comenzó nuestra historia.",
"Porque contigo descubrí un amor diferente.",
"Porque haces que quiera cuidar de ti.",
"Porque siempre estás en mis pensamientos.",
"Porque eres mi persona favorita.",
"Porque me encanta cuando compartimos momentos juntos.",
"Porque haces que los problemas parezcan más pequeños.",
"Porque eres más fuerte de lo que imaginas.",

"Porque admiro la persona que eres.",
"Porque me gusta cómo ves la vida.",
"Porque contigo aprendí que el amor está en los pequeños detalles.",
"Porque tus mensajes alegran mis días.",
"Porque siempre espero hablar contigo.",
"Porque me encanta cuando dices mi nombre.",
"Porque haces que el tiempo pase demasiado rápido.",
"Porque nunca faltan razones para sonreír contigo.",
"Porque me haces sentir completo.",
"Porque cada día descubro algo nuevo que amo de ti.",

"Porque eres única.",
"Porque contigo aprendí que amar también es cuidar.",
"Porque haces que todo sea más bonito.",
"Porque me encanta tu forma de ser.",
"Porque me haces sentir orgulloso de estar a tu lado.",
"Porque me das tranquilidad.",
"Porque siempre quiero saber cómo estás.",
"Porque haces que cualquier día sea especial.",
"Porque tus abrazos significan más de lo que imaginas.",
"Porque contigo todo vale la pena.",

"Porque eres mi mejor casualidad.",
"Porque me haces creer que los sueños sí se cumplen.",
"Porque me encanta compartir mis logros contigo.",
"Porque siempre encuentro una razón para agradecer que estés en mi vida.",
"Porque haces que quiera dar lo mejor de mí.",
"Porque me aceptas como soy.",
"Porque me apoyas cuando más lo necesito.",
"Porque contigo aprendí el verdadero significado del amor.",
"Porque siempre serás importante para mí.",
"Porque haces que mi mundo tenga más color.",

"Porque no imagino mi vida sin ti.",
"Porque eres la razón de muchas de mis sonrisas.",
"Porque contigo encontré algo que nunca quiero perder.",
"Porque me haces sentir en casa.",
"Porque amo cada pequeño detalle de ti.",
"Porque tus defectos también forman parte de la persona que amo.",
"Porque contigo aprendí que el amor también se demuestra en los pequeños gestos.",
"Porque eres la persona con la que quiero seguir creando recuerdos.",
"Porque siempre te volvería a elegir.",
"Porque haces que mi corazón sea feliz.",

"Porque cada día me enamoro un poquito más de ti.",
"Porque eres mi presente favorito.",
"Porque quiero un futuro contigo.",
"Porque me encanta imaginar todo lo que aún nos falta vivir.",
"Porque eres el mejor regalo que me dio la vida.",
"Porque cada recuerdo contigo es un tesoro.",
"Porque el mejor día fue aquel en el que te conocí.",
"Porque gracias a ti entendí lo que significa amar de verdad.",
"Porque si volviera a empezar, volvería a buscarte en aquel ensayo de tinkus para enamorarme otra vez de ti.",
"Porque aunque escribiera millones de razones, nunca alcanzarían para explicar todo lo que significas para mí. Gracias por existir, Leydi. Te amo con todo mi corazón y te elegiría una y mil veces más. ❤️"

];